### ISSUE TITLE
named_object_not_found_exception

### ISSUE THREAD

**Issue by Yeading** [opendistro/for-elasticsearch-docs#276]
response:
   '{"error":{"root_cause":[{"type":"named_object_not_found_exception","reason":"[1:16] unknown field [destination]"}],"type":"named_object_not_found_exception","reason":"[1:16] unknown field [destination]"},"status":400}',
  toString: [Function],
  toJSON: [Function] }
Alerting - MonitorService - getMonitor: { Error: [named_object_not_found_exception] [1:16] unknown field [destination]
    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:349:15)
    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:306:7)
    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)
    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4929:19)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  status: 400,
  displayName: 'BadRequest',
  message:
   '[named_object_not_found_exception] [1:16] unknown field [destination]',
  path: '/_opendistro/_alerting/monitors/ROnvN3MBKPGJ-UNNjceK',
  query: {},
  body:
   { error:
      { root_cause: [Array],
        type: 'named_object_not_found_exception',
        reason: '[1:16] unknown field [destination]' },
     status: 400 },
  statusCode: 400,
  response:
   '{"error":{"root_cause":[{"type":"named_object_not_found_exception","reason":"[1:16] unknown field [destination]"}],"type":"named_object_not_found_exception","reason":"[1:16] unknown field [destination]"},"status":400}',
  toString: [Function],
  toJSON: [Function] }

**Comment by aetter** [comment]
Hi @Yeading, we need a bit more to go on than this. What requests are you sending to generate these responses? What are you trying to achieve?
