### ISSUE TITLE
Problem running on Apple Silicon 

### ISSUE THREAD

**Issue by kidus-tiliksew** [opendistro/for-elasticsearch-docs#385]
- This issue tracker is for problems with the Open Distro for Elasticsearch *documentation*: inaccuracies, content requests, etc.
- If you need help with troubleshooting, see [the community issue tracker](https://github.com/opendistro-for-elasticsearch/community) or [the forums](https://discuss.opendistrocommunity.dev/).
- Thanks so much for helping keep us organized. Please delete this text before posting your issue.

Using [tech preview of Docker Desktop for Apple M1](https://docs.docker.com/docker-for-mac/apple-m1/) to test out open distro for elasticsearch

Ran the following command to get started 

```
docker pull amazon/opendistro-for-elasticsearch:1.12.0 
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" amazon/opendistro-for-elasticsearch:1.12.0
```

This is the output

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
OpenDistro for Elasticsearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/elasticsearch
Elasticsearch install type: rpm/deb on CentOS Linux release 7.9.2009 (Core)
Elasticsearch config dir: /usr/share/elasticsearch/config
Elasticsearch config file: /usr/share/elasticsearch/config/elasticsearch.yml
Elasticsearch bin dir: /usr/share/elasticsearch/bin
Elasticsearch plugins dir: /usr/share/elasticsearch/plugins
Elasticsearch lib dir: /usr/share/elasticsearch/lib
Detected Elasticsearch Version: x-content-7.10.0
Detected Open Distro Security Version: 1.12.0.0

### Success
### Execute this script now on all your nodes and then start all nodes
### Open Distro Security will be automatically initialized.
### If you like to change the runtime configuration 
### change the files in ../securityconfig and execute: 
"/usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh" -cd "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig" -icl -key "/usr/share/elasticsearch/config/kirk-key.pem" -cert "/usr/share/elasticsearch/config/kirk.pem" -cacert "/usr/share/elasticsearch/config/root-ca.pem" -nhnv
### or run ./securityadmin_demo.sh
### To use the Security Plugin ConfigurationGUI
### To access your secured cluster open https://<hostname>:<HTTP port> and log in with admin/admin.
### (Ignore the SSL certificate warning because we installed self-signed demo certificates)
Exception in thread "main" java.io.IOException: Cannot run program "/opt/jdk/bin/java": error=0, Failed to exec spawn helper: pid: 522, exit value: 1
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:114)
	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 522, exit value: 1
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
	... 6 more

```

**Comment by kidus-tiliksew** [comment]
Wrong place

**Comment by hanselrodrigues** [comment]
> Wrong place

What was the resolution?  I just updated to the GA release of Docker for Apple M1 and I'm still getting the same error as you.

**Comment by kidus-tiliksew** [comment]
> > Wrong place
> 
> What was the resolution? I just updated to the GA release of Docker for Apple M1 and I'm still getting the same error as you.

I haven't found any resolution. Switched to official elastic, which works

**Comment by juhasev** [comment]
I am having the same issue. I think OpenDistro maintainers should look into this.

**Comment by tjphippen** [comment]
> I am having the same issue. I think OpenDistro maintainers should look into this.

Using `docker.elastic.co/elasticsearch/elasticsearch:7.13.2-arm64` resolved issue on Apple M1 for me 🥇

**Comment by pinkminds** [comment]
Any updates on this?

**Comment by portikCoder** [comment]
Yeah, me2, although I have tried out 
`docker.elastic.co/elasticsearch/elasticsearch:7.13.2-arm64`, even the newer versions, while still getting the same error over & over again...
