### ISSUE TITLE
error use docker（docker run -d -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" --name elasticsearch amazon/opendistro-for-elasticsearch:0.8.0）

### ISSUE THREAD

**Issue by caopengfei** [opendistro/for-elasticsearch-docs#48]
OpenDistro for Elasticsearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/elasticsearch
Elasticsearch install type: rpm/deb on CentOS Linux release 7.6.1810 (Core) 
Elasticsearch config dir: /usr/share/elasticsearch/config
Elasticsearch config file: /usr/share/elasticsearch/config/elasticsearch.yml
Elasticsearch bin dir: /usr/share/elasticsearch/bin
Elasticsearch plugins dir: /usr/share/elasticsearch/plugins
Elasticsearch lib dir: /usr/share/elasticsearch/lib
Detected Elasticsearch Version: x-content-6.6.2
Detected Open Distro Security Version: 0.8.0.0

### change the files in ../securityconfig and execute: 
"/usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh" -cd "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig" -icl -key "/usr/share/elasticsearch/config/kirk-key.pem" -cert "/usr/share/elasticsearch/config/kirk.pem" -cacert "/usr/share/elasticsearch/config/root-ca.pem" -nhnv
### (Ignore the SSL certificate warning because we installed self-signed demo certificates)
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2019-04-10T07:31:40,842][INFO ][o.e.e.NodeEnvironment    ] [I4AIfZa] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [22.3gb], net total_space [25.9gb], types [rootfs]
[2019-04-10T07:31:40,843][INFO ][o.e.e.NodeEnvironment    ] [I4AIfZa] heap size [990.7mb], compressed ordinary object pointers [true]
[2019-04-10T07:31:40,845][INFO ][o.e.n.Node               ] [I4AIfZa] node name derived from node ID [I4AIfZaYReGeN5SVri92Aw]; set [node.name] to override
[2019-04-10T07:31:40,845][INFO ][o.e.n.Node               ] [I4AIfZa] version[6.6.2], pid[1], build[oss/tar/3bd3e59/2019-03-06T15:16:26.864148Z], OS[Linux/3.10.0-957.10.1.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.1/11.0.1+13]
[2019-04-10T07:31:40,845][INFO ][o.e.n.Node               ] [I4AIfZa] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-3511745295708599060, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Djava.security.policy=file:///usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config/es_security.policy, -Dclk.tck=100, -Djdk.attach.allowAttachSelf=true, -Des.cgroups.hierarchy.override=/, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=oss, -Des.distribution.type=tar]
[2019-04-10T07:31:42,237][INFO ][c.a.o.e.p.c.PluginSettings] [I4AIfZa] loading config ...
[2019-04-10T07:31:42,238][INFO ][c.a.o.e.p.c.PluginSettings] [I4AIfZa] Config: metricsLocation: /dev/shm/performanceanalyzer/, metricsDeletionInterval: 1
[2019-04-10T07:31:42,727][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] ES Config path is /usr/share/elasticsearch/config
[2019-04-10T07:31:42,806][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [I4AIfZa] OpenSSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
[2019-04-10T07:31:43,022][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [I4AIfZa] JVM supports TLSv1.3
[2019-04-10T07:31:43,023][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [I4AIfZa] Config directory is /usr/share/elasticsearch/config/, from there the key- and truststore files are resolved relatively
[2019-04-10T07:31:43,397][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [I4AIfZa] TLS Transport Client Provider : JDK
[2019-04-10T07:31:43,397][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [I4AIfZa] TLS Transport Server Provider : JDK
[2019-04-10T07:31:43,397][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [I4AIfZa] TLS HTTP Provider             : JDK
[2019-04-10T07:31:43,397][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [I4AIfZa] Enabled TLS protocols for transport layer : [TLSv1.3, TLSv1.2, TLSv1.1]
[2019-04-10T07:31:43,397][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [I4AIfZa] Enabled TLS protocols for HTTP layer      : [TLSv1.3, TLSv1.2, TLSv1.1]
[2019-04-10T07:31:43,633][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] Clustername: docker-cluster
[2019-04-10T07:31:43,693][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] Directory /usr/share/elasticsearch/config has insecure file permissions (should be 0700)
[2019-04-10T07:31:43,693][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] File /usr/share/elasticsearch/config/elasticsearch.yml has insecure file permissions (should be 0600)
[2019-04-10T07:31:43,694][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] File /usr/share/elasticsearch/config/log4j2.properties has insecure file permissions (should be 0600)
[2019-04-10T07:31:43,694][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] File /usr/share/elasticsearch/config/kirk.pem has insecure file permissions (should be 0600)
[2019-04-10T07:31:43,694][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] File /usr/share/elasticsearch/config/esnode.pem has insecure file permissions (should be 0600)
[2019-04-10T07:31:43,694][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] File /usr/share/elasticsearch/config/root-ca.pem has insecure file permissions (should be 0600)
[2019-04-10T07:31:43,694][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] File /usr/share/elasticsearch/config/esnode-key.pem has insecure file permissions (should be 0600)
[2019-04-10T07:31:43,694][WARN ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] File /usr/share/elasticsearch/config/kirk-key.pem has insecure file permissions (should be 0600)
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [aggs-matrix-stats]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [analysis-common]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [ingest-common]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [lang-expression]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [lang-mustache]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [lang-painless]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [mapper-extras]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [parent-join]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [percolator]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [rank-eval]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [reindex]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [repository-url]
[2019-04-10T07:31:43,848][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [transport-netty4]
[2019-04-10T07:31:43,849][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded module [tribe]
[2019-04-10T07:31:43,849][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded plugin [opendistro_alerting]
[2019-04-10T07:31:43,849][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded plugin [opendistro_performance_analyzer]
[2019-04-10T07:31:43,849][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded plugin [opendistro_security]
[2019-04-10T07:31:43,849][INFO ][o.e.p.PluginsService     ] [I4AIfZa] loaded plugin [opendistro_sql]
[2019-04-10T07:31:43,861][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] Disabled https compression by default to mitigate BREACH attacks. You can enable it by setting 'http.compression: true' in elasticsearch.yml
[2019-04-10T07:31:45,640][INFO ][c.a.o.s.a.i.AuditLogImpl ] [I4AIfZa] Configured categories on rest layer to ignore: [AUTHENTICATED, GRANTED_PRIVILEGES]
[2019-04-10T07:31:45,640][INFO ][c.a.o.s.a.i.AuditLogImpl ] [I4AIfZa] Configured categories on transport layer to ignore: [AUTHENTICATED, GRANTED_PRIVILEGES]
[2019-04-10T07:31:45,640][INFO ][c.a.o.s.a.i.AuditLogImpl ] [I4AIfZa] Configured Users to ignore: [kibanaserver]
[2019-04-10T07:31:45,641][INFO ][c.a.o.s.a.i.AuditLogImpl ] [I4AIfZa] Configured Users to ignore for read compliance events: [kibanaserver]
[2019-04-10T07:31:45,641][INFO ][c.a.o.s.a.i.AuditLogImpl ] [I4AIfZa] Configured Users to ignore for write compliance events: [kibanaserver]
[2019-04-10T07:31:45,649][INFO ][c.a.o.s.a.i.AuditLogImpl ] [I4AIfZa] Message routing enabled: true
[2019-04-10T07:31:45,659][WARN ][c.a.o.s.c.ComplianceConfig] [I4AIfZa] If you plan to use field masking pls configure opendistro_security.compliance.salt to be a random string of 16 chars length identical on all nodes
[2019-04-10T07:31:45,659][INFO ][c.a.o.s.c.ComplianceConfig] [I4AIfZa] PII configuration [auditLogPattern=org.joda.time.format.DateTimeFormatter@55881f40,  auditLogIndex=null]: {}
[2019-04-10T07:31:45,956][INFO ][o.e.d.DiscoveryModule    ] [I4AIfZa] using discovery type [single-node] and host providers [settings]
[2019-04-10T07:31:46,248][INFO ][c.a.o.e.p.h.c.PerformanceAnalyzerConfigAction] [I4AIfZa] PerformanceAnalyzer Enabled: true
Registering Handler
[2019-04-10T07:31:46,295][INFO ][o.e.n.Node               ] [I4AIfZa] initialized
[2019-04-10T07:31:46,295][INFO ][o.e.n.Node               ] [I4AIfZa] starting ...
[2019-04-10T07:31:46,379][INFO ][o.e.t.TransportService   ] [I4AIfZa] publish_address {172.18.0.2:9300}, bound_addresses {0.0.0.0:9300}
[2019-04-10T07:31:46,386][WARN ][o.e.b.BootstrapChecks    ] [I4AIfZa] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2019-04-10T07:31:46,392][INFO ][c.a.o.s.c.IndexBaseConfigurationRepository] [I4AIfZa] Check if .opendistro_security index exists ...
[2019-04-10T07:31:46,451][INFO ][o.e.h.n.Netty4HttpServerTransport] [I4AIfZa] publish_address {172.18.0.2:9200}, bound_addresses {0.0.0.0:9200}
[2019-04-10T07:31:46,451][INFO ][o.e.n.Node               ] [I4AIfZa] started
[2019-04-10T07:31:46,451][INFO ][c.a.o.s.OpenDistroSecurityPlugin] [I4AIfZa] 4 Open Distro Security modules loaded so far: [Module [type=REST_MANAGEMENT_API, implementing class=com.amazon.opendistroforelasticsearch.security.dlic.rest.api.OpenDistroSecurityRestApiActions], Module [type=AUDITLOG, implementing class=com.amazon.opendistroforelasticsearch.security.auditlog.impl.AuditLogImpl], Module [type=MULTITENANCY, implementing class=com.amazon.opendistroforelasticsearch.security.configuration.PrivilegesInterceptorImpl], Module [type=DLSFLS, implementing class=com.amazon.opendistroforelasticsearch.security.configuration.OpenDistroSecurityFlsDlsIndexSearcherWrapper]]
[2019-04-10T07:31:46,475][INFO ][c.a.o.s.c.IndexBaseConfigurationRepository] [I4AIfZa] .opendistro_security index does not exist yet, so we create a default config
[2019-04-10T07:31:46,477][INFO ][o.e.g.GatewayService     ] [I4AIfZa] recovered [0] indices into cluster_state
[2019-04-10T07:31:46,479][INFO ][c.a.o.s.c.IndexBaseConfigurationRepository] [I4AIfZa] Will create .opendistro_security index so we can apply default config
[2019-04-10T07:31:46,521][INFO ][o.e.c.m.MetaDataCreateIndexService] [I4AIfZa] [.opendistro_security] creating index, cause [api], templates [], shards [1]/[1], mappings []
[2019-04-10T07:31:46,526][INFO ][o.e.c.r.a.AllocationService] [I4AIfZa] updating number_of_replicas to [0] for indices [.opendistro_security]
[2019-04-10T07:31:46,694][INFO ][o.e.c.r.a.AllocationService] [I4AIfZa] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[.opendistro_security][0]] ...]).
[2019-04-10T07:31:46,701][INFO ][c.a.o.s.s.ConfigHelper   ] [I4AIfZa] Will update 'config' with /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml
[2019-04-10T07:31:46,735][ERROR][c.a.o.e.p.o.OSGlobals    ] [I4AIfZa] Error in static initialization of OSGlobals with exception: java.security.AccessControlException: access denied ("java.io.FilePermission" "/proc/self/task" "read")
java.security.AccessControlException: access denied ("java.io.FilePermission" "/proc/self/task" "read")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
	at java.security.AccessController.checkPermission(AccessController.java:895) ~[?:?]
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:322) ~[?:?]
	at java.lang.SecurityManager.checkRead(SecurityManager.java:661) ~[?:?]
	at java.io.File.list(File.java:1129) ~[?:?]
	at java.io.File.listFiles(File.java:1219) ~[?:?]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.os.OSGlobals.enumTids(OSGlobals.java:81) ~[opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.os.OSGlobals.<clinit>(OSGlobals.java:44) [opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.metrics_generator.linux.LinuxOSMetricsGenerator.getPid(LinuxOSMetricsGenerator.java:50) [opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.jvm.ThreadList.<clinit>(ThreadList.java:51) [opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.metrics.ThreadIDUtil.getNativeThreadId(ThreadIDUtil.java:31) [opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.metrics.ThreadIDUtil.getNativeCurrentThreadId(ThreadIDUtil.java:27) [opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportChannel.set(PerformanceAnalyzerTransportChannel.java:50) [opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.getShardBulkChannel(PerformanceAnalyzerTransportRequestHandler.java:78) [opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.getChannel(PerformanceAnalyzerTransportRequestHandler.java:52) [opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistro.elasticsearch.performanceanalyzer.transport.PerformanceAnalyzerTransportRequestHandler.messageReceived(PerformanceAnalyzerTransportRequestHandler.java:43) [opendistro_performance_analyzer-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistroforelasticsearch.security.ssl.transport.OpenDistroSecuritySSLRequestHandler.messageReceivedDecorate(OpenDistroSecuritySSLRequestHandler.java:194) [opendistro_security_ssl-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistroforelasticsearch.security.transport.OpenDistroSecurityRequestHandler.messageReceivedDecorate(OpenDistroSecurityRequestHandler.java:163) [opendistro_security-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistroforelasticsearch.security.ssl.transport.OpenDistroSecuritySSLRequestHandler.messageReceived(OpenDistroSecuritySSLRequestHandler.java:116) [opendistro_security_ssl-0.8.0.0.jar:0.8.0.0]
	at com.amazon.opendistroforelasticsearch.security.OpenDistroSecurityPlugin$7$1.messageReceived(OpenDistroSecurityPlugin.java:652) [opendistro_security-0.8.0.0.jar:0.8.0.0]
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:687) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) [elasticsearch-6.6.2.jar:6.6.2]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.6.2.jar:6.6.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[2019-04-10T07:31:46,967][INFO ][o.e.c.m.MetaDataMappingService] [I4AIfZa] [.opendistro_security/kZ94xDrnSKi3ayI5mwf-Qw] create_mapping [security]
[2019-04-10T07:31:47,071][INFO ][c.a.o.s.s.ConfigHelper   ] [I4AIfZa] Will update 'roles' with /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml
[2019-04-10T07:31:47,092][INFO ][o.e.c.m.MetaDataMappingService] [I4AIfZa] [.opendistro_security/kZ94xDrnSKi3ayI5mwf-Qw] update_mapping [security]
[2019-04-10T07:31:47,144][INFO ][c.a.o.s.s.ConfigHelper   ] [I4AIfZa] Will update 'rolesmapping' with /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml
[2019-04-10T07:31:47,160][INFO ][o.e.c.m.MetaDataMappingService] [I4AIfZa] [.opendistro_security/kZ94xDrnSKi3ayI5mwf-Qw] update_mapping [security]
[2019-04-10T07:31:47,192][INFO ][c.a.o.s.s.ConfigHelper   ] [I4AIfZa] Will update 'internalusers' with /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml
[2019-04-10T07:31:47,205][INFO ][o.e.c.m.MetaDataMappingService] [I4AIfZa] [.opendistro_security/kZ94xDrnSKi3ayI5mwf-Qw] update_mapping [security]
[2019-04-10T07:31:47,223][INFO ][c.a.o.s.s.ConfigHelper   ] [I4AIfZa] Will update 'actiongroups' with /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/action_groups.yml
[2019-04-10T07:31:47,233][INFO ][o.e.c.m.MetaDataMappingService] [I4AIfZa] [.opendistro_security/kZ94xDrnSKi3ayI5mwf-Qw] update_mapping [security]
[2019-04-10T07:31:47,269][INFO ][c.a.o.s.c.IndexBaseConfigurationRepository] [I4AIfZa] Default config applied
[2019-04-10T07:31:47,293][INFO ][c.a.o.s.c.IndexBaseConfigurationRepository] [I4AIfZa] Node 'I4AIfZa' initialized

**Comment by aetter** [comment]
Hi @caopengfei, that looks like a success message to me. Can you run `curl -XGET https://localhost:9200 -u admin:admin -k` and get a response?

**Comment by scull7** [comment]
I'm receiving the same error when I run:
```
docker run -p 9200:9200 -p 9600:9600 -e "discovery.type=single-node" amazon/opendistro-for-elasticsearch:latest
```

I receive the following output:
```
OpenDistro for Elasticsearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/elasticsearch
Elasticsearch install type: rpm/deb on CentOS Linux release 7.6.1810 (Core) 
Elasticsearch config dir: /usr/share/elasticsearch/config
Elasticsearch config file: /usr/share/elasticsearch/config/elasticsearch.yml
Elasticsearch bin dir: /usr/share/elasticsearch/bin
Elasticsearch plugins dir: /usr/share/elasticsearch/plugins
Elasticsearch lib dir: /usr/share/elasticsearch/lib
Detected Elasticsearch Version: x-content-7.2.0
Detected Open Distro Security Version: 1.2.0.0

### Success
### Execute this script now on all your nodes and then start all nodes
### Open Distro Security will be automatically initialized.
### If you like to change the runtime configuration 
### change the files in ../securityconfig and execute: 
"/usr/share/elasticsearch/plugins/opendistro_security/tools/securityadmin.sh" -cd "/usr/share/elasticsearch/plugins/opendistro_security/securityconfig" -icl -key "/usr/share/elasticsearch/config/kirk-key.pem" -cert "/usr/share/elasticsearch/config/kirk.pem" -cacert "/usr/share/elasticsearch/config/root-ca.pem" -nhnv
### or run ./securityadmin_demo.sh
### To use the Security Plugin ConfigurationGUI
### To access your secured cluster open https://<hostname>:<HTTP port> and log in with admin/admin.
### (Ignore the SSL certificate warning because we installed self-signed demo certificates)
Exception in thread "main" java.lang.RuntimeException: starting java failed with [137]
output:

error:
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111)
	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79)
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57)
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89)
```

When I attempt to connect:
```
curl -XGET https://localhost:9200 -u admin:admin -k
curl: (7) Failed to connect to localhost port 9200: Connection refused
```

Also, `docker ps` does not show any opendistro container.
