### ISSUE TITLE
Opensearch crashing on Macbook Pro M1 Max (Docker)

### ISSUE THREAD

**Issue by pinkminds** [opendistro/for-elasticsearch-docs#509]
When running a fresh install of Opendistro for Elasticsearch 1.13.2 on a Macbook Pro M1 MAX, the docker image crashes after a few minutes running with this feedback in the log:

`Exception in thread "main" java.io.IOException: Cannot run program "/opt/jdk/bin/java": error=0, Failed to exec spawn helper: pid: 340, exit value: 1
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1142)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:114)
at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:88)
at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:59)
at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:137)
at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:95)
Caused by: java.io.IOException: error=0, Failed to exec spawn helper: pid: 340, exit value: 1
at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:313)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1109)
... 6 more`

Is this a known issue? Linked to Apple’s M1 MAX silicon? Or unrelated?
Any ideas on how to fix?

Many thanks,
Kevin

PS: docker for desktop also shows a ‘amd64’ performance warning label.

**Comment by pinkminds** [comment]
If I need to run any other diagnostics, just let me know.

**Comment by stockholmux** [comment]
@pinkminds I think I responded on your forum post but this is a known issue. Open Distro docker doesn't support `arm64` but OpenSearch does.

**Comment by pinkminds** [comment]
Yes indeed, changing to Opensearch did the trick. Thx again!
