### ISSUE TITLE
debian openssl documentation

### ISSUE THREAD

**Issue by gna582** [opendistro/for-elasticsearch-docs#87]
Dear developers,

as you recommend I would like to use Openssl. I followed the documentation posted here: https://opendistro.github.io/for-elasticsearch-docs/docs/security-configuration/tls/#openssl
and tried to adapt it for debian stretch.

These are my installed packages. As far as I understand libapr1 should provide the APR.
```
ii  openssl                              1.1.0j-1~deb9u1                   amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  libapr1:amd64                        1.5.2-5                           amd64        Apache Portable Runtime Library
ii  libaprutil1:amd64                    1.5.4-3                           amd64        Apache Portable Runtime Utility Library
ii  libnetty-tcnative-java               1.1.33.Fork26-1                   all          Tomcat native fork for Netty
ii  libnetty-tcnative-jni                1.1.33.Fork26-1                   amd64        Tomcat native fork for Netty (JNI library)
```
I used the libnetty-tcnative and plan to use systemd's ExecStartPre to copy the current jar into the opendistro-security directory so I don't have to manually update it.
```
-rw-r--r-- 1 root root 70760 Jun 13 08:44 /usr/share/elasticsearch/plugins/opendistro_security/netty-tcnative.jar
MD5SUM:
ab4c77c0dc2590547fc96608d4136f2d  /usr/share/elasticsearch/plugins/opendistro_security/netty-tcnative.jar
```
But opendistro-security does not pick it up:
```
[2019-06-13T09:06:05,237][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [mes-any-mailsearch-dev002-mes_any_mailsearch1] OpenSSL not available (this is not an error, we simply fallback to built-in JDK SSL
) because of java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
```

I can change the error by using netty-tcnative-2.0.25.Final-linux-x86_64.jar from 
https://repo1.maven.org/maven2/io/netty/netty-tcnative/2.0.25.Final/netty-tcnative-2.0.25.Final-linux-x86_64.jar.
This is the error when using the other netty-tcnative version:
```
[2019-06-13T09:34:52,425][INFO ][c.a.o.s.s.DefaultOpenDistroSecurityKeyStore] [mes-any-mailsearch-dev002-mes_any_mailsearch1] OpenSSL not available (this is not an error, we simply fallback to built-in JDK SSL
) because of java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
```

Please help me understand how to use Openssl with debian.

I installed opendistro via the elasticsearch plugin manager and use the elasticsearch puppet module https://forge.puppet.com/elastic/elasticsearch

ES: 6.7.1
Opendistro: 0.9.0.0

Thank you!

**Comment by aetter** [comment]
Hi @gna582, thanks a bunch for reporting. I'm able to reproduce on both RHEL and Debian, so I'm working with the development team to figure out what the heck the plugin is looking for. 😕

I'll let you know what I find out/modify the documentation as appropriate.

**Comment by aetter** [comment]
Hi @gna582, for now, we're recommending a statically-linked JAR that has OpenSSL, APR, and netty-tcnative. I'm not wild about the solution---people should be able to use system packages---so I'm leaving this issue open until we can get better steps into the documentation or a cleaner solution into the product. In the meantime, you can grab the file you need [here](https://bintray.com/floragunncom/netty-tcnative/download_file?file_path=netty-tcnative-openssl-1.1.0j-static-2.0.20.Final-non-fedora-linux-x86_64.jar) and drop it into `plugins/opendistro_security`. I've also updated the docs.

**Comment by gna582** [comment]
Hi @aetter,
thank you for the quick reply and the fast clarification!

Tested that static jar and it does indeed enable openssl in opendistro_security.

I must admit that the thought of having to keep up with openssl and netty security update cycles to keep that static jar safe is unappealing.

I'll have a read how insecure CBC actually is and maybe test if performance without openssl is sufficient. (Context: https://github.com/floragunncom/search-guard/issues/310#issuecomment-372145935)

Thank you!

**Comment by gna582** [comment]
For the people who came here via google you should also note that openssl 1.1.0 doesn't support tls1.3, so it also needs to be disabled like this:
```
opendistro_security.ssl.http.enabled_protocols: 
- "TLSv1.1" 
- "TLSv1.2" 
```

If you don't do that, you will see errors like this on the master:
```
[2019-06-14T15:44:01,281][WARN ][i.n.c.ChannelInitializer ] [mes-any-mailsearch-dev002-mes_any_mailsearch1] Failed to initialize a channel. Closing: [id: 0xc6c3f2c4, L:/10.90.20.194:9200 - R:/10.90.20.194:3729
4]
java.lang.IllegalArgumentException: Protocol TLSv1.3 is not supported.
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.setEnabledProtocols(ReferenceCountedOpenSslEngine.java:1516) ~[netty-handler-4.1.32.Final.jar:4.1.32.Final]
        at com.amazon.opendistroforelasticsearch.security.ssl.DefaultOpenDistroSecurityKeyStore.createHTTPSSLEngine(DefaultOpenDistroSecurityKeyStore.java:525) ~[opendistro_security_ssl-0.9.0.0.jar:0.9.0.0]
        at com.amazon.opendistroforelasticsearch.security.ssl.http.netty.OpenDistroSecuritySSLNettyHttpServerTransport$SSLHttpChannelHandler.initChannel(OpenDistroSecuritySSLNettyHttpServerTransport.java:115) 
~[opendistro_security_ssl-0.9.0.0.jar:0.9.0.0]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:115) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:107) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:480) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:86) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:255) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470) [netty-transport-4.1.32.Final.jar:4.1.32.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) [netty-common-4.1.32.Final.jar:4.1.32.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
I think this also relates to https://github.com/opendistro-for-elasticsearch/security-ssl/pull/10

**Comment by aetter** [comment]
Hi @gna582, @hardik-k-shah mentioned that commit to me, and I wasn't sure why he brought it up. Thanks for the clarification. It's worth noting that if you're using Java 11, performance is apparently quite similar to OpenSSL. It's just that OpenSSL has a large advantage over Java 8.

**Comment by aetter** [comment]
At this point, our recommendation is essentially "use Java 11," so I've made a minor change to that page and am going to close this issue out.
